# Setup
title:        MR-Hub
tagline:      Open-access software tools for the ISMRM community
url:          http://ismrm.github.io
baseurl:      "/mrhub"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
